import { Book } from "@mui/icons-material";

export const rows= [
    {
        id: 1,
        username: 'Tibbyyoung',
        amount: 50,
        desc: 'Amount charged for using automated funding',
        status: 'successful',
        iwallet: 578,
        fwallet: 528,
        ip: "127.0.0.1:A",
        server: '',
        ref: 'MNFY634676843686486346887',
        date: Date.now(),
        note: '',
        action: <Book />
    },
    {
        id: 2,
        username: 'Tibbyyoung',
        amount: 50,
        desc: 'Amount charged for using automated funding',
        status: 'successful',
        iwallet: 578,
        fwallet: 528,
        ip: "127.0.0.1:A",
        server: '',
        ref: 'MNFY634676843686486346887',
        date: Date.now(),
        note: '',
        action: <Book />
    },
    {
        id: 3,
        username: 'Tibbyyoung',
        amount: 50,
        desc: 'Amount charged for using automated funding',
        status: 'successful',
        iwallet: 578,
        fwallet: 528,
        ip: "127.0.0.1:A",
        server: '',
        ref: 'MNFY634676843686486346887',
        date: Date.now(),
        note: '',
        action: <Book />
    },
    {
        id: 4,
        username: 'Tibbyyoung',
        amount: 50,
        desc: 'Amount charged for using automated funding',
        status: 'successful',
        iwallet: 578,
        fwallet: 528,
        ip: "127.0.0.1:A",
        server: '',
        ref: 'MNFY634676843686486346887',
        date: Date.now(),
        note: '',
        action: <Book />
    },
    {
        id: 5,
        username: 'Tibbyyoung',
        amount: 50,
        desc: 'Amount charged for using automated funding',
        status: 'successful',
        iwallet: 578,
        fwallet: 528,
        ip: "127.0.0.1:A",
        server: '',
        ref: 'MNFY634676843686486346887',
        date: Date.now(),
        note: '',
        action: <Book />
    },
    {
        id: 6,
        username: 'Tibbyyoung',
        amount: 50,
        desc: 'Amount charged for using automated funding',
        status: 'successful',
        iwallet: 578,
        fwallet: 528,
        ip: "127.0.0.1:A",
        server: '',
        ref: 'MNFY634676843686486346887',
        date: Date.now(),
        note: '',
        action: <Book />
    },
    {
        id: 7,
        username: 'Tibbyyoung',
        amount: 50,
        desc: 'Amount charged for using automated funding',
        status: 'successful',
        iwallet: 578,
        fwallet: 528,
        ip: "127.0.0.1:A",
        server: '',
        ref: 'MNFY634676843686486346887',
        date: Date.now(),
        note: '',
        action: <Book />
    },
    {
        id: 8,
        username: 'Tibbyyoung',
        amount: 50,
        desc: 'Amount charged for using automated funding',
        status: 'successful',
        iwallet: 578,
        fwallet: 528,
        ip: "127.0.0.1:A",
        server: '',
        ref: 'MNFY634676843686486346887',
        date: Date.now(),
        note: '',
        action: <Book />
    },
    {
        id: 9,
        username: 'Tibbyyoung',
        amount: 50,
        desc: 'Amount charged for using automated funding',
        status: 'successful',
        iwallet: 578,
        fwallet: 528,
        ip: "127.0.0.1:A",
        server: '',
        ref: 'MNFY634676843686486346887',
        date: Date.now(),
        note: '',
        action: <Book />
    },
    {
        id: 10,
        username: 'Tibbyyoung',
        amount: 50,
        desc: 'Amount charged for using automated funding',
        status: 'successful',
        iwallet: 578,
        fwallet: 528,
        ip: "127.0.0.1:A",
        server: '',
        ref: 'MNFY634676843686486346887',
        date: Date.now(),
        note: '',
        action: <Book />
    },
    {
        id: 11,
        username: 'Tibbyyoung',
        amount: 50,
        desc: 'Amount charged for using automated funding',
        status: 'successful',
        iwallet: 578,
        fwallet: 528,
        ip: "127.0.0.1:A",
        server: '',
        ref: 'MNFY634676843686486346887',
        date: Date.now(),
        note: '',
        action: <Book />
    },
    {
        id: 12,
        username: 'Tibbyyoung',
        amount: 50,
        desc: 'Amount charged for using automated funding',
        status: 'successful',
        iwallet: 578,
        fwallet: 528,
        ip: "127.0.0.1:A",
        server: '',
        ref: 'MNFY634676843686486346887',
        date: Date.now(),
        note: '',
        action: <Book />
    },
    {
        id: 13,
        username: 'Tibbyyoung',
        amount: 50,
        desc: 'Amount charged for using automated funding',
        status: 'successful',
        iwallet: 578,
        fwallet: 528,
        ip: "127.0.0.1:A",
        server: '',
        ref: 'MNFY634676843686486346887',
        date: Date.now(),
        note: '',
        action: <Book />
    },
]